version: '3.3'

services:
  app:
    build: .
    entrypoint: ["/bin/sh", "-c", "sh .docker/entrypoint.sh"]
    container_name: heo-app
    env_file:
        - ./.env 
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/mariadb
    container_name: heo-db
    restart: always
    env_file:
        - ./.env 
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - .docker/dbdata:/var/lib/mariadb/data
      - .docker/mariadb/init.sql:/data/aplication/init.sql
    command: --init-file /data/aplication/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: 123
